### ISSUE TITLE
swgetheaders is not defined

### ISSUE THREAD

**Issue by LukyVj** [gmetais/sw-get-headers#1]
If I followed your README.md,
Once I called the `swgetheaders-page.js` via a require(); I write this line : 
`swgetheaders.registerServiceWorker('./vendors/swgetheaders-worker.js');`

And I got an error : `swgetheaders is not defined` 

Any idea here the error comes from ? 
Thanks.

**Comment by gmetais** [comment]
Hello Lucas,

Did you correctly include the script, then require swgetheaders like the following?

<script src="/some-path/swgetheaders-page.js"></script>

var swgetheaders = require('swgetheaders');

**Comment by gmetais** [comment]
Sorry I forgot a script tag:

<script src="/some-path/swgetheaders-page.js"></script>

<script>
var swgetheaders = require('swgetheaders');
...
</script>
